default:
  navigation:
    - title: Produkty
      subtitle: Kategorie
      url: /products
      items:
        - :title: Olejki
          :url: /t/olejki
        - :title: Susz
          :url: /t/susz
        - :title: Kosmetyki
          :url: /t/kosmetyki
      promo_banners:
        - title: OLEJKI
          url: /t/olejki
          image: 'meganav/promo_banner_left-first-category.jpg'
        - title: KOSMETYKI
          url: /t/kosmetyki
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: O Hemp Champ
      subtitle: Categories
      url: "#about"
    - title: Więcej o CBD
      subtitle: Categories
      url: "#faq"
